-- CreateTable
CREATE TABLE "SPXHost" (
    "username" STRING NOT NULL,
    "password" STRING NOT NULL,
    "name" STRING NOT NULL,
    "lastname" STRING NOT NULL,
    "status" STRING NOT NULL,

    CONSTRAINT "SPXHost_pkey" PRIMARY KEY ("username")
);

-- CreateTable
CREATE TABLE "SPXGuest" (
    "username" STRING NOT NULL,
    "password" STRING NOT NULL,
    "name" STRING NOT NULL,
    "lastname" STRING NOT NULL,
    "status" STRING NOT NULL,

    CONSTRAINT "SPXGuest_pkey" PRIMARY KEY ("username")
);

-- CreateTable
CREATE TABLE "SPXSession" (
    "id" STRING NOT NULL,
    "hostId" STRING NOT NULL,
    "guestId" STRING NOT NULL,
    "start" TIMESTAMP(3) NOT NULL,
    "end" TIMESTAMP(3) NOT NULL,
    "status" STRING NOT NULL,

    CONSTRAINT "SPXSession_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SPXSessionProduct" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sessionId" STRING NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "productId" STRING NOT NULL,
    "productName" STRING NOT NULL,
    "productUrl" STRING NOT NULL,

    CONSTRAINT "SPXSessionProduct_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SPXSessionWishlist" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sessionId" STRING NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "productId" STRING NOT NULL,
    "productName" STRING NOT NULL,
    "productUrl" STRING NOT NULL,
    "quantity" INT4 NOT NULL,

    CONSTRAINT "SPXSessionWishlist_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SPXSessionCart" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sessionId" STRING NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "productId" STRING NOT NULL,
    "productName" STRING NOT NULL,
    "productUrl" STRING NOT NULL,
    "quantity" INT4 NOT NULL,

    CONSTRAINT "SPXSessionCart_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SPXSessionReview" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sessionId" STRING NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "stars" INT4 NOT NULL,
    "comment" STRING NOT NULL,

    CONSTRAINT "SPXSessionReview_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SPXHost_username_key" ON "SPXHost"("username");

-- CreateIndex
CREATE UNIQUE INDEX "SPXGuest_username_key" ON "SPXGuest"("username");

-- CreateIndex
CREATE UNIQUE INDEX "SPXSessionReview_sessionId_key" ON "SPXSessionReview"("sessionId");

-- AddForeignKey
ALTER TABLE "SPXSession" ADD CONSTRAINT "SPXSession_hostId_fkey" FOREIGN KEY ("hostId") REFERENCES "SPXHost"("username") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SPXSession" ADD CONSTRAINT "SPXSession_guestId_fkey" FOREIGN KEY ("guestId") REFERENCES "SPXGuest"("username") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SPXSessionProduct" ADD CONSTRAINT "SPXSessionProduct_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "SPXSession"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SPXSessionWishlist" ADD CONSTRAINT "SPXSessionWishlist_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "SPXSession"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SPXSessionCart" ADD CONSTRAINT "SPXSessionCart_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "SPXSession"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SPXSessionReview" ADD CONSTRAINT "SPXSessionReview_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "SPXSession"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
